aletheia/urls.py
from django.urls import path

from aletheia import views

app_name = "aletheia"
urlpatterns = [
    path('config/register/', views.registration_config, name="register_config"),
    path('register/', views.register, name="register"),
    path('config/login/', views.login_config, name="login_config"),
    path('login/', views.login_view, name="login")
]

aletheia/templates/webauthn/login.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

    {% include "webauthn/scripts.html" %}

    <h1>{% trans "Sign In" %}</h1>

    <form id="form_login" class="login" onsubmit="event.preventDefault(); login_webauth(username.value)" method="POST" action="{% url "aletheia:login" %}">
        {% csrf_token %}
        {{ form.as_p }}
        {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
        <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
        <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
    </form>

{% endblock %}

aletheia/templates/webauthn/scripts.html
{% load static %}
<script src="{% static "aletheia/base64url-arraybuffer.min.js" %}"></script>
<script src="{% static "aletheia/js.cookie.min.js" %}"></script>
<script>
    if (!window.PublicKeyCredential) {
        if(typeof create_error === "function") {
            create_error("No WebAuthN Support Detected!")
        }
        else {
            alert("No WebAuthN Support Detected!")
        }
    }

    async function register(register_status_callback = (status, msg) => {}) {
        register_status_callback("start", undefined);

        let registration_config = await fetch("{% url "aletheia:register_config" %}")
            .then(response => response.json())
            .then(login_config => {
                login_config.user.id = window.base64url.decode(login_config.user.id);
                login_config.challenge = window.base64url.decode(login_config.challenge);
                if (login_config.hasOwnProperty("excludeCredentials")) {
                    for (let i = 0; i < login_config.excludeCredentials.length; i++) {
                        login_config.excludeCredentials[i].id = window.base64url.decode(login_config.excludeCredentials[i].id);
                    }
                }
                return login_config
            })
            .catch(reason => register_status_callback("fail", reason));

        let credential;
        try {
            credential = await navigator.credentials.create({
                publicKey: registration_config
            });
        }
        catch (error) {
            register_status_callback("fail", error)
            return;
        }

        const encoded = {
            "rawId": window.base64url.encode(credential.rawId),
            "id": credential.id,
            "type": credential.type,
            "response": {
                "attestationObject": window.base64url.encode(credential.response.attestationObject),
                "clientDataJSON": window.base64url.encode(credential.response.clientDataJSON),
            }
        }

        await fetch("{% url "aletheia:register" %}",
            {
                "method": "POST",
                "headers": {"X-CSRFToken": Cookies.get('csrftoken')},
                "mode": "same-origin",
                "body": JSON.stringify(encoded)
            })
            .then(response => {
                if (response.status === 200) {
                    register_status_callback("success", undefined);
                } else {
                    register_status_callback("fail", response.statusText);
                }
            });
    }

    async function login_webauth(username, login_status_callback = (status, msg) => {}) {
        login_status_callback("start", undefined);

        let form_data = new FormData();
        form_data.append("login", username);

        let login_config = await fetch("{% url "aletheia:login_config" %}",
            {
                "method": "POST",
                "headers": {"X-CSRFToken": Cookies.get('csrftoken')},
                "mode": "same-origin",
                body: form_data
            })
            .then(response => response.json())
            .then(login_config => {
                login_config.challenge = window.base64url.decode(login_config.challenge);
                if (login_config.hasOwnProperty("allowCredentials")) {
                    for (let i = 0; i < login_config.allowCredentials.length; i++) {
                        login_config.allowCredentials[i].id = window.base64url.decode(login_config.allowCredentials[i].id);
                    }
                }
                return login_config
            })
            .catch(reason => login_status_callback("fail", reason));

        let credential;
        try {
            credential = await navigator.credentials.get({
                publicKey: login_config
            });
        } catch (error) {
            login_status_callback("fail", error)
            return;
        }

        const encoded = {
            "rawId": window.base64url.encode(credential.rawId),
            "id": credential.id,
            "type": credential.type,
            "response": {
                "authenticatorData": window.base64url.encode(credential.response.authenticatorData),
                "clientDataJSON": window.base64url.encode(credential.response.clientDataJSON),
                "signature": window.base64url.encode(credential.response.signature),
                "userHandle": window.base64url.encode(credential.response.userHandle),
            }
        }

        document.getElementById("{{ form.client_id.id_for_label }}").value = credential.id;
        document.getElementById("{{ form.webauthn_data.id_for_label }}").value = JSON.stringify(encoded);
        document.getElementById("form_login").submit();
    }

    {%  url "aletheia:login" as login_url %}
    {% if request.path == login_url %}
        {# The user has to be saved as a cookie because only an HTTP Redirect is done after knowing the login succeeded. #}
        const user = Cookies.get("django-aletheia-webauthn-user");
        if (user) {
            document.getElementById("{{ form.username.id_for_label }}").value = user;
            login_webauth(user);
        }
    {% endif %}


</script>