webauthnauth/urls.py
from django.urls import path

from webauthnauth import views

app_name = "webauthnauth"
urlpatterns = [
    path('config/register/', views.registration_config, name="register_config"),
    path('register/', views.register, name="register"),
    path('config/login/', views.login_config, name="login_config"),
    path('login/', views.login_view, name="login")
]

webauthnauth/views.py
import json
import secrets
from json import JSONDecodeError

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.http.response import HttpResponseRedirectBase
from django.views import View
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.edit import FormMixin
from webauthn import (
    generate_registration_options,
    verify_registration_response,
    options_to_json,
    base64url_to_bytes, generate_authentication_options
)
from webauthn.helpers.structs import (
    AttestationConveyancePreference,
    AuthenticatorSelectionCriteria,
    UserVerificationRequirement,
    PublicKeyCredentialDescriptor,
    ResidentKeyRequirement,
    RegistrationCredential,
)

from webauthnauth import settings
from webauthnauth.forms import WebAuthNLoginForm
from webauthnauth.models import AuthData
from webauthnauth.util import base64encode, base64decode


class HttpUnprocessableEntity(HttpResponseRedirectBase):
    status_code = 422


@login_required
def registration_config(request):
    challenge = secrets.token_urlsafe(64)

    request.session["challenge"] = challenge

    currently_registered = AuthData.objects.filter(user=request.user).all()

    options = generate_registration_options(
        rp_id=settings.RELYING_PARTY_ID,
        rp_name=settings.RELYING_PARTY_NAME,
        user_id=str(request.user.id),
        user_name=f"{request.user.first_name} {request.user.last_name}",
        user_display_name=request.user.username,
        attestation=AttestationConveyancePreference.NONE,
        authenticator_selection=AuthenticatorSelectionCriteria(
            #            authenticator_attachment=AuthenticatorAttachment.PLATFORM,
            resident_key=ResidentKeyRequirement.PREFERRED
        ),
        exclude_credentials=[PublicKeyCredentialDescriptor(id=base64decode(auth_data.credential_id)) for auth_data in
                             currently_registered],
        challenge=challenge.encode("utf-8"),
        timeout=300000,
    )
    return HttpResponse(content=options_to_json(options), content_type="application/json")


@login_required()
def register(request):
    if "challenge" not in request.session:
        messages.error(request, "Missing challenge in this session.", fail_silently=True)
        return HttpUnprocessableEntity(f"Missing challenge in this session.")
    else:
        challenge = request.session.get("challenge")

    registration_response = request.body
    try:
        registered_key = verify_registration_response(
            credential=RegistrationCredential.parse_raw(registration_response.decode("utf-8")),
            expected_challenge=challenge.encode("utf-8"),
            expected_origin=settings.EXPECTED_ORIGIN,
            expected_rp_id=settings.RELYING_PARTY_ID,
            require_user_verification=False,
        )
    except Exception as e:
        messages.error(request, f"Registration failed. Error: {e}", fail_silently=True)
        return HttpUnprocessableEntity(f"Registration failed. Error: {e}")

    AuthData.objects.create(
        user=request.user,
        credential_id=base64encode(registered_key.credential_id),
        public_key=base64encode(registered_key.credential_public_key),
    )

    messages.success(request, "WebAuthN Client registered.", fail_silently=True)
    return HttpResponse("Success")


def login_config(request):
    challenge = secrets.token_urlsafe(64)

    request.session["challenge"] = challenge

    if "login" not in request.POST:
        messages.error(request, f"Missing \"login\" POST field", fail_silently=True)
        return HttpUnprocessableEntity(f"Missing \"login\" POST field")
    else:
        username = request.POST["login"]

    users_keys = AuthData.objects.filter(user__username=username).all()

    options = generate_authentication_options(
        rp_id=settings.RELYING_PARTY_ID,
        challenge=challenge.encode("utf-8"),
        timeout=120000,
        user_verification=UserVerificationRequirement.DISCOURAGED,
        allow_credentials=[PublicKeyCredentialDescriptor(id=base64decode(auth_data.credential_id))
                           for auth_data in users_keys],
    )

    return HttpResponse(content=options_to_json(options), content_type="application/json")


class LoginView(View, FormMixin, TemplateResponseMixin):
    template_name = "webauthn/login.html"
    form_class = WebAuthNLoginForm

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        try:
            login_response_json = json.loads(request.body.decode("utf-8"))
        except JSONDecodeError as error:
            message = f"Login failed. Failed parsing JSON. Error: {error}"
            messages.error(request, message, fail_silently=True)
            return HttpUnprocessableEntity(message)

        user = authenticate(request,
                            # TODO: this dict access might fail
                            credential_id=base64encode(base64url_to_bytes(login_response_json["id"])),
                            data=request.body.decode("utf-8"))
        if user is None:
            return HttpResponseForbidden(f"Login failed.")

        login(request, user)
        messages.success(request, f"Successfully signed in as {user.username}.", fail_silently=True)

        return HttpResponse("Success")


login_view = LoginView.as_view()

webauthnauth/templates/webauthn/scripts.html
<script src="https://cdn.jsdelivr.net/gh/herrjemand/Base64URL-ArrayBuffer@latest/lib/base64url-arraybuffer.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js" integrity="sha256-0H3Nuz3aug3afVbUlsu12Puxva3CP4EhJtPExqs54Vg=" crossorigin="anonymous"></script>
<script>
    async function register(register_status_callback = (status, msg) => {}) {
        register_status_callback("start", undefined);

        let registration_config = await fetch("{% url "webauthnauth:register_config" %}")
            .then(response => response.json())
            .then(login_config => {
                login_config.user.id = window.base64url.decode(login_config.user.id);
                login_config.challenge = window.base64url.decode(login_config.challenge);
                if (login_config.hasOwnProperty("excludeCredentials")) {
                    for (let i = 0; i < login_config.excludeCredentials.length; i++) {
                        login_config.excludeCredentials[i].id = window.base64url.decode(login_config.excludeCredentials[i].id);
                    }
                }
                return login_config
            })
            .catch(reason => register_status_callback("fail", reason));

        let credential;
        try {
            credential = await navigator.credentials.create({
                publicKey: registration_config
            });
        }
        catch (error) {
            register_status_callback("fail", error)
            return;
        }

        const encoded = {
            "rawId": window.base64url.encode(credential.rawId),
            "id": credential.id,
            "type": credential.type,
            "response": {
                "attestationObject": window.base64url.encode(credential.response.attestationObject),
                "clientDataJSON": window.base64url.encode(credential.response.clientDataJSON),
            }
        }

        await fetch("{% url "webauthnauth:register" %}",
            {
                "method": "POST",
                "headers": {"X-CSRFToken": Cookies.get('csrftoken')},
                "mode": "same-origin",
                "body": JSON.stringify(encoded)
            })
            .then(response => {
                if (response.status === 200) {
                    register_status_callback("success", undefined);
                } else {
                    register_status_callback("fail", response.statusText);
                }
            });
    }

    async function login_webauth(username, login_status_callback = (status, msg) => {}) {
        login_status_callback("start", undefined);

        let form_data = new FormData();
        form_data.append("login", username);

        let login_config = await fetch("{% url "webauthnauth:login_config" %}",
            {
                "method": "POST",
                "headers": {"X-CSRFToken": Cookies.get('csrftoken')},
                "mode": "same-origin",
                body: form_data
            })
            .then(response => response.json())
            .then(login_config => {
                login_config.challenge = window.base64url.decode(login_config.challenge);
                if (login_config.hasOwnProperty("allowCredentials")) {
                    for (let i = 0; i < login_config.allowCredentials.length; i++) {
                        login_config.allowCredentials[i].id = window.base64url.decode(login_config.allowCredentials[i].id);
                    }
                }
                return login_config
            })
            .catch(reason => login_status_callback("fail", reason));

        let credential;
        try {
            credential = await navigator.credentials.get({
                publicKey: login_config
            });
        } catch (error) {
            login_status_callback("fail", error)
            return;
        }

        const encoded = {
            "rawId": window.base64url.encode(credential.rawId),
            "id": credential.id,
            "type": credential.type,
            "response": {
                "authenticatorData": window.base64url.encode(credential.response.authenticatorData),
                "clientDataJSON": window.base64url.encode(credential.response.clientDataJSON),
                "signature": window.base64url.encode(credential.response.signature),
                "userHandle": window.base64url.encode(credential.response.userHandle),
            }
        }

        await fetch("{% url "webauthnauth:login" %}",
            {
                "method": "POST",
                "headers": {"X-CSRFToken": Cookies.get('csrftoken')},
                "mode": "same-origin",
                "body": JSON.stringify(encoded)
            })
            .then(response => {
                if (response.status === 200) {
                    window.location.replace("{% url "index" %}");
                    login_status_callback("success", undefined);
                } else {
                    login_status_callback("fail", response.statusText);
                }
            })
    }

</script>